new-branch-v1
CodeSeoul/event_member_management pull request #39
Opened 2022-03-04 15:21 UTC by ConnorSmiley

Sorry, I uninstall YARN but it screwed up my npm. So I had to start over

2022-03-04 15:27 UTC, ConnorSmiley commented on client/src/components/Footer.js
> +      <div className="footer-col">
I didn't chose the className="footer-col"

2022-03-04 15:28 UTC, ConnorSmiley commented on client/src/components/Header.js
> +        <h1 className="header-title">Event Manager</h1>
changed from "header-header" => "header-title"

2022-03-04 15:29 UTC, ConnorSmiley commented on client/src/components/Search.js
> +      <input type="text" className="searchbar-input" placeholder="Search" />
Renamed from "searchbar--input" => "searchbar-input"

2022-06-21 20:39 UTC, TheBeege requested changes
Minor readme fix. Everything else looks okay, pending linting matches.

2022-06-21 20:39 UTC, TheBeege commented on README.md
> +- ~~Track and report on event
Some bad formatting here

2022-07-06 13:41 UTC, closed without merging